### ISSUE TITLE
Overlay cannot access room data or something ?

### ISSUE THREAD

**Issue by Paloys** [viddie/ConsistencyTrackerMod#19]
I have this error happening each time I change room in the tracker : 
```
Uncaught TypeError: Cannot read properties of undefined (reading 'left')
    at updateRoomInLayout (CCTOverlay.js:983:63)
    at XMLHttpRequest.xhr.onreadystatechange (CCTOverlay.js:286:21)
```
![image](https://user-images.githubusercontent.com/40764414/160082796-d3a3b4b6-baa9-439b-8ca5-d0a2626fb653.png)
This is what I have with the tracker, and it doesn't change at any time completing a chapter.
Does anyone have an idea ?

**Comment by Paloys** [comment]
I mostly said tracker instead of overlay, sorry about that

**Comment by viddie** [comment]
Hmmm the path looks weird in the chapter display. There is only 1 bar that is fully green, but unless the map you are testing this with only has 1 room there should be more than that.
If you are playing a chapter from the base game, did you accidentally enable and disable the option in mod settings "Record Path"? This would override the premade path with the only room you are currently in.
If you are playing a custom chapter, did you correctly record the path? Like: Enable the "Record Path" option in the first room, then move through the chapter as you usually would and then disable the option "Record Path" in the last room that you want to track?
I know that there are a few issues when you switch between rooms that are on the path and rooms that are not on the path, and an incorrect path obviously amplifies that...

**Comment by Paloys** [comment]
The screenshot was taken after completing 3A from start to right before the last room.
I just completed the chapter normally, without touching the settings, but the overlay stayed like this.

For some reason, while trying again today after wiping my data (I had already tried to do so), it began to work.

I'm going to close the issue, i have no idea why it worked again though.
