### ISSUE TITLE
game crash on macOS if speedrun tool is not installed

### ISSUE THREAD

**Issue by DemoJameson** [viddie/ConsistencyTrackerMod#28]
for some reason macOS don't like the `SlAction`, [so I add a `SafeAdd()` to workaround it](https://github.com/DemoJameson/CelesteSpeedrunTool/commit/de8e292e6ffa2450daf973745b989c0bde0364ad)
use `SaveLoadAction.SafeAdd()` instead of `SaveLoadAction.Add()` should fix it

similar crash: https://discord.com/channels/403698615446536203/975158983251886091/975158983251886091

**Comment by viddie** [comment]
Oh dang, I'll look into that one. Thanks for the report!
